import { clx as ClxFunction } from "./clx.ts";
import { curry as CurryFunction } from "./curry.ts";
import { debounce as DebounceFunction } from "./debounce.ts";
import { formatPrice as FormatFunction } from "./format.ts";
import { relative as UrlFunction } from "./url.ts";
import { useId as UseIdFunction } from "./useId.ts";
import { useOffer as UseOfferFunction } from "./useOffer.ts";
import { usePlatform as UsePlatformFunction } from "./usePlatform.tsx";
import { useSuggestions as UseSuggestionsFunction } from "./useSuggestions.ts";
import { useUI as UseUIFunction } from "./useUI.ts";
import { useVariantPossibilities as UseVariantPossibilitiesunction } from "./useVariantPossibilities.ts";

export const clx = ClxFunction;
export const curry = CurryFunction;
export const debounce = DebounceFunction;
export const formatPrice = FormatFunction;
export const relative = UrlFunction;
export const useId = UseIdFunction;
export const useOffer = UseOfferFunction;
export const usePlatform = UsePlatformFunction;
export const useSuggestion = UseSuggestionsFunction;
export const useUI = UseUIFunction;
export const useVariantPossibilities = UseVariantPossibilitiesunction;
